github.com:
    users:
        monkeybones702:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: monkeybones702
